#!/bin/bash
file=/var/lib/mender/uboot_type.txt
if [ ! -e "$file" ]; then
	echo "Uboot_type file does not exist. Please make sure you run get_uboot_type.c and the file /var/lib/mender/uboot_type.txt exists."
	exit 1
fi
read retVal < /var/lib/mender/uboot_type.txt
set -e
STATE="$1"
FILES="$2"

case "$STATE" in
    ArtifactInstall)
	if [ $retVal -eq 1 ]; then
		dd if=/dev/mmcblk1 of=/dev/mmcblk1 bs=1k count=2048 skip=33 seek=2081 && sync
        	ret=$?
        	if [ $ret gt 0 ]; then
                	echo "Copying primary flash.bin to secondary failed ...."
			exit 1
        	fi
	fi 
        dd if="$FILES"/files/signed_flash.bin of=/dev/mmcblk1 bs=1K seek=33 && sync
        ret=$?
        if [ $ret gt 0 ]; then
                echo "Writing signed_flash.bin to flash failed ...."
		exit 1
        fi
        ;;
esac
exit 0
